### ISSUE TITLE
error in 'bash universal-framework.sh'

### ISSUE THREAD

**Issue by reicamargo** [ianlevesque/mopub-xamarin-ios#6]
There's some errors when you run the command 'bash universal-framework.sh'
The following build commands failed:

The following build commands failed:

```
CompileC build/MoPub.build/Release-iphoneos/MoPub.build/Objects-normal/armv7/AdColonyCustomEvent.o MoPubSDK/AdNetworkSupport/AdColony/AdColonyCustomEvent.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

(1 failure)

```
CompileC build/MoPub.build/Release-iphonesimulator/MoPub.build/Objects-normal/i386/AdColonyCustomEvent.o MoPubSDK/AdNetworkSupport/AdColony/AdColonyCustomEvent.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

(1 failure)
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: ./build/release-iphonesimulator/MoPub.framework/MoPub (No such file or directory)

I couldn't figure out the problem. =\

**Comment by dh-dave-hanson** [comment]
Were you able to figure out the issue? It sounds to me like one of the steps before lipo failed as well, that is probably the root of the issue (though perhaps the bash script should exit earlier in a situation like that)
