### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by vbisbest** [ianlevesque/mopub-xamarin-ios#8]
Hi, just curious if you have a binding library for Xamarin Android.   Thanks for your efforts.

Ray

**Comment by dh-dave-hanson** [comment]
Hi Ray, see https://github.com/AudioAddict/mopub-xamarin-android

I see that the main branch is out of date, but the video ads branch is what we are using internally.

**Comment by vbisbest** [comment]
Thanks, that is pretty far out of date as mopub is on 4.11 now.  And I really need banners and interstatials.  Hopefully an update can get pushed soon.

**Comment by vbisbest** [comment]
On more question if I may.  How did you create the single MoPub aar file?  Specifically in your video example, its mopub-android-release.aar.  I have tried all kinds of gradlew commands but it always generates multiple aar files and all are mopub-sdk-(x).   Thanks.
